# Generated by Django 5.2.6 on 2025-12-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_task_comment_task_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramAuth',
        ),
    ]
