# Generated by Django 5.2.7 on 2025-12-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduagent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='building_type',
            field=models.CharField(choices=[('school', 'Школа'), ('library', 'Библиотека'), ('lab', 'Лаборатория'), ('gym', 'Спортзал'), ('art', 'Арт-студия')], default='school', help_text='Тип здания в стиле EduPlay', max_length=50),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение для задания', null=True, upload_to='exercises/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.IntegerField(default=1, help_text='Уровень задания (1-5)'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML/CSS'), ('django', 'Django'), ('algorithm', 'Алгоритмы'), ('math', 'Математика')], max_length=50),
        ),
    ]
